import Game from './16-slider';

const game = new Game();

game.right();
console.log(game.grid);
game.right();
console.log(game.grid);
game.right();
console.log(game.grid);
game.right();
console.log(game.grid);
game.down();
console.log(game.grid);
game.left();
console.log(game.grid);
game.left();
console.log(game.grid);
game.left();
console.log(game.grid);
game.left();
console.log(game.grid);
game.down();
console.log(game.grid);
game.right();
console.log(game.grid);
game.right();
console.log(game.grid);
game.right();
console.log(game.grid);
game.right();
console.log(game.grid);